import 'package:flutter/material.dart';
import './generated/GeneratedGroup801Widget.dart';
import './generated/GeneratedSearchWidget.dart';
import './generated/GeneratedGroup4Widget.dart';
import './generated/GeneratedRectangle301Widget.dart';
import './generated/GeneratedButtonAtomWidget.dart';
import './generated/GeneratedTabBarWidget.dart';

/* Frame iPhone 11 Pro / X - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 8.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 35.0,
                child: GeneratedRectangle301Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 27.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 14.278409004211426,
                top: 64.54545593261719,
                right: null,
                bottom: null,
                width: 345.7215881347656,
                height: 669.1363525390625,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 6.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 363.0,
                height: 162.0,
                child: GeneratedGroup801Widget(),
              ),
              Positioned(
                left: 299.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 36.0,
                child: GeneratedButtonAtomWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 60.0,
                child: GeneratedTabBarWidget(),
              )
            ]),
      ),
    ));
  }
}
